Add max completion time to taskInfo (#881)
mesos/chronos pull request #884
Opened 2018-09-06 22:55 UTC by edi33416

2018-09-06 22:57 UTC, edi33416 commented
This cherry-picks #881 onto stable, in order to provide `maxCompletionTime` to version 2.x

@gkleiman can you please review?

2018-09-06 23:00 UTC, edi33416 commented
Please note that I had to remove the `concurrent` field, as it wasn't present on `stable`.
See errors
```
[ERROR] /home/fawkes/chronos/src/main/scala/org/apache/mesos/chronos/utils/JobSerializer.scala:130: error: value concurrent is not a member of org.apache.mesos.chronos.scheduler.jobs.BaseJob
[ERROR]     json.writeBoolean(baseJob.concurrent)
```

```
[ERROR] /home/fawkes/chronos/src/main/scala/org/apache/mesos/chronos/scheduler/jobs/Jobs.scala:127: error: value concurrent overrides nothing
[ERROR]                              @JsonProperty override val concurrent: Boolean = false,
[ERROR]                                                         ^                                                                                                                                                  
[ERROR] /home/fawkes/chronos/src/main/scala/org/apache/mesos/chronos/scheduler/jobs/Jobs.scala:166: error: value concurrent overrides nothing
[ERROR]                                @JsonProperty override val concurrent: Boolean = false,
[ERROR]                                                           ^  
```

2018-09-12 21:59 UTC, gkleiman requested changes
Thanks! Just two minor comments =).

2018-09-12 21:59 UTC, gkleiman commented on src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala
> +      val maxCompletionTime = DurationInfo.newBuilder().setNanoseconds(job.maxCompletionTime * pow(10, 9).toLong).build()
I should have noticed this on the previous PR, but better late than never =).

I think we should use `scala.concurrent.duration.Duration` here, like this:

```
val maxCompletionTime = DurationInfo.newBuilder().setNanoseconds(Duration(job.maxCompletionTime.seconds.toNanos).build()
```

2018-09-12 21:59 UTC, gkleiman commented on src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala
> +      taskInfo.setMaxCompletionTime(maxCompletionTime)
Remove this line.

2018-09-13 10:51 UTC, edi33416 commented on src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala
> +      taskInfo.setMaxCompletionTime(maxCompletionTime)
Oops. Will remove

2018-09-13 11:22 UTC, edi33416 commented on src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala
> +            .setNanoseconds(job.maxCompletionTime.seconds.toNanos)
@gkleiman is this ok, or would you prefer
`.setNanoseconds(Duration(job.maxCompletionTime, SECONDS).toNanos)` ?

2018-09-29 20:34 UTC, gkleiman commented
LGTM, thank you so muchj!

2018-09-29 20:34 UTC, merged